using DbManager.Parser;
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;


namespace DbManager
{
  public class ColumnDefinition
  {
    public enum DataType { String, Int, Double}

    public DataType Type;
    public string Name { get; private set; }


    public ColumnDefinition(DataType type, string name)
    {
      if (string.IsNullOrEmpty(name)) { return; }
      Type = type;
      Name = name;
    }
    private const string Delimiter = "->";
    private const string DelimiterEncoded = "[ARROW]";

    private static string Encode(string value)
    {
      //TODO DEADLINE 1.C: Encode the delimiter in the value
      string[] values = value.Split(Delimiter);
      return values[0] + DelimiterEncoded + values[1];
    }

    private static string Decode(string value)
    {
      //TODO DEADLINE 1.C: Decode the delimiter in the value
      string[] values = value.Split(DelimiterEncoded);
      return values[0] + Delimiter + values[1];
    }

    public string AsText()
    {
      //TODO DEADLINE 1.C: Return the column as a string with the name and the type separated by the delimiter
      return Name + Delimiter + Type.ToString();
            
    }

    public static ColumnDefinition Parse(string value)
    {
      //TODO DEADLINE 1.C: Parse the column's name and type from a string generated by AsText()
      string[] values = value.Split(Delimiter);
      if (values[1] == "String") return new ColumnDefinition(DataType.String, values[0]);
      if (values[1] == "Double") return new ColumnDefinition (DataType.Double, values[0]);
      return new ColumnDefinition (DataType.Int, values[0]);
    }
  }
}
